### ISSUE TITLE
Multiple Video Events/Tracks for Chords?

### ISSUE THREAD

**Issue by Evauation** [otomad/VegasScripts#3]
**So the Otomad Script is insanely astonishing for what it has. Everything about it is borderline excellent.** 
I do have a suggestion. It's based on how audio generates the chords from the MIDI file selected. I think it should do the same thing with video, with an option to toggle the visual generation for chords. Like when the script generates the visuals, it should have the ability to make chord video tracks as well, making it easier to create chord visuals in the YTPMV/Otomad.

I also have created a [Google Doc](https://docs.google.com/document/d/1PEkh0_WFDLUAYGD-YzIDNXUQiAKqogEvpuRQhfqz9ng/edit#) that's essentially an index for the majority of Otomad Helper, made to guide users on what to do and what features do what. This was intentionally made for another community so some things might sound odd or biased, so I apologize for that.

And yeah, keep doing what you're doing, your work is absolutely amazing.

**Comment by otomad** [comment]
Ok, I will add a new option to toggle the visual generation for chords.

In fact, the script generates multiple tracks for chords by default, but according to my original idea, it only generates one track, so I only need to disable this feature separately.

Thank you for your document for script and the tutorial video. I can put the link in the README.

**Comment by Evauation** [comment]
It does? I thought it didn't and it only applied to audio tracks...

**Comment by otomad** [comment]
> ‎它能做到吗？我以为它没有，它只适用于音轨...‎

Oh no, I meant I'll add this feature in the next update.

It is currently only disabled at the code level.

**Comment by otomad** [comment]
> It does? I thought it didn't and it only applied to audio tracks...

Oh no, I meant I'll add this feature in the next update.

It is currently only disabled at the code level.

**Comment by Evauation** [comment]
Awesome! Hope to see it released in the future!

Edit: Also the Roadmap Page leads to a 404, assuming it doesn't exist?

**Comment by otomad** [comment]
### Answers to some questions about your documentation
* **Audio - Freeze last frame**: If the MIDI note is longer than the audio track clip, it will be trimmed at the track clip rather than stretched to the length of the MIDI note. NOTE: This will conflict with the "Legato", so you can only choose between the two.
* **Audio - Create Groups**: If checked, video and audio clips represented by a MIDI note will create a group. This will make it easier to change the position or length of the audio and video clips simultaneously. If this is a chord, all the audio clips will also be in the same group.
* **Audio - Tuning Methods - Fool with Tunning**: Lock the stretch and the pitch, then determine the pitch based on the clip stretch length. In fact, this option is added to play by myself, and it is not practical.
* **Video - Visual Effects - "Unlimited"**: It was renamed to "Whirl", not removed.
* **Video - Parameters - Start/End Size**: "Anything over 100 will look whird". However, if they over 100, then it will only reduce the video clip size.

**Comment by otomad** [comment]
> Edit: Also the Roadmap Page leads to a 404, assuming it doesn't exist?

I edited the README yesterday, and Roadmap has not been written yet :) .

**Comment by otomad** [comment]
Sorry my English is not very good, if you find inappropriate or incoherent or more appropriate terminology in the script, welcome to give me suggestions.

**Comment by Evauation** [comment]
No worries, and thank you so much for helping me with some errors and missing details. I'm also aware of the lack of English too, but that's no problem.

> Thank you for your document for script and the tutorial video. I can put the link in the README.

I would probably have to do some rewriting to make it more like an official document since I made this doc with haste and it's not perfect!

But yeah, awesome and thanks again.

**Comment by otomad** [comment]
> I'm also aware of the lack of English too, but that's no problem.

After all, I hope that some words are more appropriate, so that it looks more professional.

Everyone is free to make suggestions, this project is still relatively deserted.

**Comment by otomad** [comment]
I'm planning a big update in the future (v5.x), and this is the prototype of it. *(Chinese)*
![屏幕截图 2022-06-04 154534](https://user-images.githubusercontent.com/56647156/177910498-3b6bd8df-db83-45ea-8ec6-58b7d5dc8558.png)

**Comment by Evauation** [comment]
> Everyone is free to make suggestions, this project is still relatively deserted.

Its scripts like these that desire more attention because of how good they are, the awareness and such is what keeps them going, and I wanted to bring more awareness when I had the chance.

> I'm planning a big update in the future (v5.x), and this is the prototype of it. _(Chinese)_ 


That is really cool, you are really outdoing yourself man.

**Comment by otomad** [comment]
One more point:

If your MIDI has changing tempos, it **DO** will support changing tempo.

**Comment by otomad** [comment]
@Evauation Oh no, in your new documentation, "BPM Tempo - Cursor" ??? What's this?

And if your MIDI has changing tempos, it DO will support changing tempo. You can test a dynamic MIDI generated by FL, there will be a new option.

**Comment by Evauation** [comment]
How did I mistyped that, I didn't see that in my revisions...

Edit: Fixed now, it was suppose to say "Project", not "Cursor"
That somehow slipped my mind.

**Comment by otomad** [comment]
And **tuning method**, pitch shift audio effect. The stretching is not locked, you can individually control "stretch" and "lock stretch and pitch". It just use "pitch shift" plugin in audio FX instead of directly tuning with plus and minus key on keyboard. Note: in Vegas 13~15, the only tuning method is it. Because other methods are not supported in those versions. With this method, generating will be very slowly, you can see progress bar only by using this method.

**Lock stretch and pitch**, like old style remixing, just adjust the stretch to change the pitch. It also known as Resample.

**Comment by otomad** [comment]
The new version has been released, thank you for your support. If you have any other questions, please create an issue.

**Latest version:** https://github.com/otomad/VegasScripts/releases/latest

**Comment by Evauation** [comment]
~~I don't know if commenting reopens the issue~~
Edit: ok it doesn't. But very awesome that the update came out!

I have updated the documentation to include all v4.19 features as best as I could.
It would also be useful to use Discord for better communication too.
