### ISSUE TITLE
Help! how do i fix this?

### ISSUE THREAD

**Issue by ArthurRibeirooo** [otomad/VegasScripts#55]
### Vegas Pro Version

Vegas Pro 14

### Otomad Helper Version

Latest

### Describe the bug

its method is not supported!
![bandicam 2023-09-03 16-43-09-348](https://github.com/otomad/OtomadHelper/assets/142274686/f7fb4943-6517-4562-8a04-f465bcdcfa39)

**Comment by Evauation** [comment]
Please show more details by clicking Details and screenshot the log or copy and paste here.

**Comment by Evauation** [comment]
Also if you could, please describe what you were doing at the time of the error.

**Comment by Evauation** [comment]
https://github.com/otomad/OtomadHelper/issues/25 - Common Questions / FAQ
https://github.com/otomad/OtomadHelper/releases/latest - Always make sure to download the correct version for your Vegas Pro version.

This issue has become stale. The most likely scenario for this issue is that you may have used a feature incompatible with Vegas Pro 14 since Otomad Helper works best in Vegas Pro 16 and up. While Otomad Helper supports 13, 14 and 15. Not all features will be available or work on those versions. 

So if any new relevant information comes up (details of the error and/or steps to replicate), you may open another issue.
